version: '2'
services:
  flask:
    build: .
    volumes:
      - ../app/src:/app
    ports:
      - "80:80"
  nginx:
    image: nginx:alpine
    volumes:
      - ../app/static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    links:
      - flask
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80