version: '3'
services:
  flask:
    build: .
    restart: unless-stopped
    command: "-d"
    volumes:
      - ../src:/app
    ports:
      - "5000:5000"
  nginx:
    image: nginx:alpine
    volumes:
      - ../src/static:/app/static
      - ./nginx.conf:/tmp/default.conf.template
    ports:
      - "80:80"
    links:
      - flask
