version: '3'
services:
  flask:
    build: .
    restart: unless-stopped
    volumes:
      - ../src:/app
    ports:
      - "5000:5000"
  nginx:
    image: nginx:alpine
    volumes:
      - ../src/static:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - flask
